# Base configs
baseurl: "/photography"
url: "http://jtal.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Me"
subtitle: "Bleep Bloop Bleep!"
author: "jtal"
bio: "I am."
publicise: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/something"
  twitter: "https://www.twitter.com/something"
  instagram: "https://www.instagram.com/something"
  dribbble: "https://dribbble.com/something"
  linkedin: "https://in.linkedin.com/in/something"
  github: "https://www.github.com/something"
  
